---
- name: playbook for EiM devices 

# Execute scripts on all cisco firewalls
  hosts: "firewall_cisco,&DEGT"

  gather_facts: false
  connection: network_cli

  roles:
    - ../Ansible/firewall_cisco 


