---
- name: playbook for EiM devices 

# Execute scripts on all cisco firewalls
  hosts: "firewall_cisco,&DEGT"

  gather_facts: false
  connection: network_cli

  tasks:
    - name: ACL config for Dehong
      cisco.asa.asa_config:
        lines:

      save_when: changed 



